apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    service: frontend
  type: LoadBalancer